version: "3.2"
services:
    zosConnect:
        image: icr.io/zosconnect/ibm-zcon-designer:3.0.59
        environment:
            - BAQ_NETWORK=BAQCA
            - BAQ_APPLID=BAQCA
            - CICS_NAME=cicsConn
            - CICS_HOST=10.242.64.200
            - CICS_PORT=57027
            - KEYSTORE=zc-pot-designer.p12
            - KEYSTORE_PASSWORD=${KPASS}
            - TRUSTSTORE=zc-pot-designer-truststore.p12
            - TRUSTSTORE_PASSWORD=${TPASS}
            - HTTPS_PORT=9443
        ports:
            - "9443:9443"
        volumes:
            - ../zc-pot-api:/workspace/project
            - ./logs/:/logs/
            - ./certs:/config/resources/security/:ro
            - ./defaults:/config/configDropins/defaults:ro
