version: "3.2"
services:
    zosConnect:
        image: icr.io/zosconnect/ibm-zcon-designer:3.0.57
        environment:
            - BAQ_NETWORK=BAQCA
            - BAQ_APPLID=BAQCA
            - CICS_HOST=169.62.161.37
            - CICS_PORT=57027
            - HTTPS_PORT=9443
            - KEYSTORE_PASSWORD=${KPASS}
            - TRUSTSTORE_PASSWORD=${TPASS}
        ports:
            - "9443:9443"
        volumes:
            - ../zc-pot-api:/workspace/project
            - ./logs/:/logs/
            - ./certs:/config/resources/security/:ro
            - ./defaults:/config/configDropins/defaults:ro
